### ISSUE TITLE
[Dedicated Server] Tool Broken

### ISSUE THREAD

**Issue by Peekofwar** [dvdvideo1234/PhysPropertiesAdv#2]
While it's not producing any script errors, it isn't working correctly (at least on my dedicated server).

Problem: Not only does it not have a menu in the right pane, but the tool name and button descriptions are missing strings and just appear with  `#tool.physprop_adv.name`.for example.

It does seem like the script is kind of working, I can right-mouse to copy materials, but it says "invalid" whenever I try to left-mouse on a prop. It's not producing any script errors in the client or server consoles.

(This is on a dedicated server if that helps)

The title and button descriptions are missing:
![image](https://user-images.githubusercontent.com/10189526/174452939-409f9278-9036-46c5-9d20-edfe33911ae3.png)

The tool menu is missing in the right pane:
![image](https://user-images.githubusercontent.com/10189526/174452970-6540089d-b579-455e-807a-54db27376b24.png)

Kind of working, but won't apply:
![image](https://user-images.githubusercontent.com/10189526/174453029-e9b60dab-f5db-4063-8033-bf4b5f427fd8.png)

Client console:
![image](https://user-images.githubusercontent.com/10189526/174453084-87f36af2-623b-4492-b1d9-d2a7f00564c2.png)

Server console:
![image](https://user-images.githubusercontent.com/10189526/174453122-44b486c3-44ea-413e-8a7a-1f3d80a7acbe.png)

**Comment by dvdvideo1234** [comment]
@Peekofwar 

Tested OK on my personal local server. This will no longer miss translations as it is loaded on autorun. Test it again and if it works I will close this.

**Comment by Peekofwar** [comment]
> Tested OK on my personal local server. This will no longer miss translations as it is loaded on autorun. Test it again and if it works I will close this.

Nothing seems to have changed. I checked that the workshop item was indeed updated, and added it to the server... It still has the same issues.

**Comment by dvdvideo1234** [comment]
What error message does it give now? Is it a different one?
Maybe you cannot run [`CompileFile`](https://wiki.facepunch.com/gmod/Global.CompileFile) for some reason

It is possible you are using folders containing capital letters and your Gmod version does not like this.

**Comment by dvdvideo1234** [comment]
Assuming the user @Peekofwar did not rename the the tool main folder to lower case for Linux or updated the GMA.

**Comment by dvdvideo1234** [comment]
Hello, @Peekofwar 

I tried utilizing the general Gmod localization procedure. It will not need dedicated Lua to be compiled:
https://wiki.facepunch.com/gmod/Addon_Localization

I am currently testing this branch. You can try it too if it works for you I will merge it and apply it to all my addons ;)
https://github.com/dvdvideo1234/PhysPropertiesAdv/pull/3/files
