### ISSUE TITLE
Change readme.md and Workshop page description

### ISSUE THREAD

**Issue by WolfeStrider** [dvdvideo1234/PhysPropertiesAdv#4]
The readme.md should have text added under the How to install the extension section about the fact that you also need to install the material data so it would look like this instead:

"
How to install the extension

Just clone [this repo](https://github.com/dvdvideo1234/PhysPropertiesAdv) in your addons folder, then copy [the configuration files](https://github.com/dvdvideo1234/PhysPropertiesAdv/tree/master/data/physprop_adv/materials) inside
your DATA folder garrysmod/data/physprop_adv/materials/*.txt
and then copy [the material configuration files] (https://github.com/dvdvideo1234/PhysPropertiesAdv/tree/master/data/material_adv/materials) inside
your DATA folder garrysmod/data/material_adv)/materials/*.txt
"

For the Workshop page description you need to change the text from:

"2. Material data
..garrysmod/data/physprop_adv/materials"
to:
"2. Material data
..garrysmod/data/material_adv/materials"

**Comment by dvdvideo1234** [comment]
This repo is two tools in one. Phys-prop and material ADV are two different tools. More likely it need them both:
https://github.com/dvdvideo1234/PhysPropertiesAdv/tree/master/lua/weapons/gmod_tool/stools
